---
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: ksail-default
nodes:
  - role: control-plane
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
    extraPortMappings:
      - containerPort: 30010
        hostPort: 80
        protocol: TCP
      - containerPort: 30011
        hostPort: 443
        protocol: TCP
containerdConfigPatches:
- >-
  [plugins."io.containerd.grpc.v1.cri".registry]
    config_path = "/etc/containerd/certs.d"
