---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pinniped
  namespace: pinniped
spec:
  interval: 5m
  chart:
    spec:
      chart: pinniped
      version: 2.3.5
      sourceRef:
        kind: HelmRepository
        name: pinniped
  # https://github.com/bitnami/charts/blob/main/bitnami/pinniped/values.yaml
  values:
    supervisor:
      service:
        # Supervisor service should not use LoadBalancer type
        public:
          type: ClusterIP
      ingress:
        enabled: false
        hostname: pinniped-supervisor.pinniped.svc.cluster.local
        tls: true
