---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-controllers
  namespace: flux-system
spec:
  interval: 60m
  retryInterval: 2m
  timeout: 3m
  dependsOn: []
  sourceRef:
    kind: OCIRepository
    name: flux-system
  path: infrastructure/controllers
  prune: true
  wait: true
