---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - certificates/default-certificate.yaml
  - certificates/pinniped-certificate.yaml
  - cluster-issuers/selfsigned-cluster-issuer.yaml
  - federation-domains/github-federation-domain.yaml
  - identity-providers/github-identity-provider.yaml
  - ingress-routes/pinniped-supervisor-tcp.yaml
  - rbac
