---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 10m
  chart:
    spec:
      chart: traefik
      version: 33.0.0
      sourceRef:
        kind: HelmRepository
        name: traefik
  # https://github.com/traefik/traefik-helm-chart/blob/master/traefik/values.yaml
  values:
    # To remove the default - "--global.sendanonymoususage" argument
    globalArguments:
      - --global.checknewversion
    ports:
      web:
        nodePort: 30010
        redirectTo:
          port: websecure
      websecure:
        nodePort: 30011
    tlsStore:
      default:
        defaultCertificate:
          secretName: default-certificate-tls
    service:
      type: NodePort

