apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: pinniped-supervisor
  namespace: pinniped
spec:
  entryPoints:
    - websecure
  routes:
    - match: HostSNI(`pinniped-supervisor.pinniped.svc.cluster.local`)
      services:
        - name: pinniped-supervisor
          port: 443
  tls:
    secretName: pinniped-supervisor-tls
    passthrough: true
