apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pinniped-certificate
  namespace: pinniped
spec:
  secretName: pinniped-supervisor-tls
  dnsNames:
    - pinniped-supervisor.pinniped.svc.cluster.local
  commonName: pinniped-certificate
  subject:
    organizations:
      - Project Pinniped
    organizationalUnits:
      - Pinniped PoC
  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer
